name: Build

on: push

jobs:
  build-site:
    name: Gatsby Build
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: npm install, build
        run: |
          npm install
          npm run build
