name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: npm run lhci
